version: '3.9'
services:
  fastapi:
    build: ./fastapi-ai
    container_name: fastapi
    ports:
      - '8000:8000'
    env_file:
      - ./fastapi-ai/.env
    volumes:
      - ./fastapi-ai/weights:/fastapi/weights
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: always
