version: '3.9'
services:
  fastapi:
    build: .
    container_name: fastapi
    ports:
      - '80:8000'
    env_file:
      - .env
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
