version: '3.9'
services:
  smartbow:
    build:
      context: .
      dockerfile: fastapi-ai/Dockerfile
    container_name: smartbow
    ports:
      - '8000:8000'
    env_file:
      - ./fastapi-ai/.env
    volumes:
      - ./fastapi-ai/weights:/smartbow/weights
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: always
